<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>BaseClasses_V2</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SliccDB\SliccDB.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ObservableCollections" Version="3.3.4" />
    </ItemGroup>

</Project>
