<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Procedural</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\base\BaseClasses\BaseClasses.csproj" />
      <ProjectReference Include="..\base\BaseClasses\BaseClasses.csproj" />
    </ItemGroup>

</Project>
