<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\Icons\" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.3" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
        <PackageReference Include="Avalonia.FreeDesktop" Version="12.0.3" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
        <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.11" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\base\BaseClasses\BaseClasses.csproj" />
        <ProjectReference Include="..\AI\AIGenerator\AIGenerator.csproj" />
        <ProjectReference Include="..\StructuredNarrative\StructuredNarrative.csproj" />
     </ItemGroup>
    
    <ItemGroup>
      <Compile Update="Views\Windows\ConfirmWindow.axaml.cs">
        <DependentUpon>ConfirmWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Windows\ParamEditWindow.axaml.cs">
        <DependentUpon>ParamEditWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Windows\RelationEditWindow.axaml.cs">
        <DependentUpon>RelationEditWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
